### PR TITLE
add image of module dependencies

### PR DESCRIPTION
**Pull request by mixmix**
I wanna see that diagram in this repo because it helps add context to why these

I know the image is out of date already... how should we solve that

### CODE REVIEW

**Comment by staltz** [comment]
> I know the image is out of date already... how should we solve that

`mermaid` is a good way of writing diagrams as text and having them render automatically. They're supported in Hackmd and GitLab, but unfortunately not GitHub.

**Comment by mixmix** [comment]
yeah I think as long as we commit something that makes it easy to run some script to generate a diagram that would be sweet

**Comment by davegomez** [comment]
Does anybody knows what's the name of that type of diagram?

**Comment by christianbundy** [comment]
> Does anybody knows what's the name of that type of diagram?

It's a 'network diagram' or 'graph diagram', the boring old tech to render these is called GraphViz -- here's my favorite online viewer: https://dreampuf.github.io/GraphvizOnline/

**Review by christianbundy — COMMENTED** [review]
I like the idea of a diagram but I'm worried that this is already outdated and we don't have a process for generating a new one. I'm also feeling hesitant to add a build step to our governance repository, but maybe I'm just being a Luddite.

I'd be comfortable putting assets like logos in this repo, but I think I'd like to put build artifacts somewhere else.

**Comment by mixmix** [comment]
yeah I think putting it elsewhere as a nice-to-have is a great idea @christianbundy 
Sorry for taking up bandwidth with this.

CLOSING

**Pull request closed without merging**
