### PR TITLE
Default to Prettier and ESlint

### LINKED ISSUE #25: Code style
This is one of my least favorite conversations on the planet, but I think we should have it once in one place instead of having the same conversations in bits and pieces all over the modules. **What are the minimum 'code style' standards that we want to enforce?** Here are my preferences:

- I'd prefer to use popular convention instead of inventing our own.
- I'd prefer to use boring conventions so that our code is familiar and predictable.
- I'd prefer to separate concerns so that our formatting (syntax) and logic (semantics) can be changed independently.

I'd suggest:

- **[ESLint:Recommended](https://eslint.org/docs/rules/)** for semantics -- Most/all modern linters use ESLint under the hood, and all of the most common + boring + uncontroversial rules have been added to a 'recommended' ruleset that comes with ESLint. This is the smallest and most agreeable ruleset I'm aware of, and applying it to our modules has been quick and easy.
- **[Prettier](https://prettier.io/)** for syntax -- 41 times more npm downloads than StandardJS, 18x more GitHub dependents, formats dozens of languages (Markdown, JS-in-Markdown (!), CSS, GraphQL, etc), and produces an uncontroversial style that's boring and familiar enough for everyone.

I was originally thinking that maintainers could just use their own code style, but I doubt that we want to change code style every 6 months or whatever, so maybe we should just have a default code style so that we can decide on and then move on to actually-interesting problems. Anyone have any big blocking concerns about ESLint + Prettier, or suggestions for more-boring style guides? My goal is to hit the sweet point between 'useless' and 'controversial'.

### PR DESCRIPTION
**Pull request by christianbundy**
Our modules don't conform to any style guide for code formatting or
code quality, which means we all pull toward our personal preference
rather than some 'good enough' middle ground that we can all agree on.

Common style guides make cooperation easier and create a high-pass
filter for disagreements and churn. Automatic code formatting and
code-quality rules are helpful to set expectations that are accessible
and predictable.

Writing a style guide takes lots of work, and there's a large risk that
any custom style guide will be unfamiliar to the vast majority of people
who want to contribute to our projects. My preference is to use style
guides which are popular (familiar) and uncontroversial (boring), which
should make the style guide resistant to unnecessary future churn.

This commit adds a rule to default to Prettier and ESLint, which gives
us code formatting rules for most languages and code-quality rules for
languages that are compatible with ESLint (JavaScript, JSX, TypeScript,
and others).

Fixes: https://github.com/ssb-js/ssb-js/issues/25

### CODE REVIEW

**Review by staltz — APPROVED** [review]

**Comment by soapdog** [comment]
Just to be clear: a project should follow one or the other, or, one and the other?

**Comment by staltz** [comment]
@soapdog I think it's both.

**Review by soapdog — APPROVED** [review]

**Comment by christianbundy** [comment]
Yep! Prettier for formatting (e.g. no empty lines at the end of files) , ESLint for code-quality rules (e.g. no unused variables).

**Comment by staltz** [comment]
Hey @mixmix or @arj03, could we get your review?

**Comment by mixmix** [comment]
I'm on board with the principle  100%
I am a no on Prettier (I won't hard block and exit the org, but I'll feel frustrated and annoyed when I do maintenance)

I really tried with Prettier but I felt like I was being hit with a stick the whole time.

I would propose Standard because it catches most of the junk which is problematic while still giving you some space about eg how you newline a ternary.

Thanks for the mention @staltz

**Review by arj03 — APPROVED** [review]

**Comment by arj03** [comment]
I don't have any strong opinions on this matter.

**Comment by staltz** [comment]
We have 3 approvals, so technically this could be merged, but I'm concerned about @mixmix's wishes. Would there be a way for Prettier to be "out of your way", perhaps if it runs in a git commit hook, does it still bother you?

**Comment by mixmix** [comment]
Nice idea. 
I mainly want my editor to help me spot problems as I go, but I feel like with Prettier it highlights not - problems (imo), which makes solving imprudent things harder.

I'm up for trying it (Prettier) if most people would rather it than standard.
We can also try anything for 3-6 months

**Comment by staltz** [comment]
@mixmix I don't know how you have used Prettier, but I use it in either two ways: (1) my editor automatically applies it whenever I save the file, (2) git commit hook. So I never see "warnings" or requests from Prettier, it just does stuff for me.

I don't like how it formats conditional ternaries, but I've also come to the point where I "quit" trying to format the code, so in the end of the day, code formatting becomes a concern that I entirely "outsource" to Prettier, letting me focus on logical coding. I often code in an entirely sloppy manner because I know Prettier will come by and format it for me, e.g.:

I type:

```js
function greet(age){console.log(''+age+' years old')}
```

Then I save, then Prettier makes it look like this:

```js
function greet(age) {
  console.log('' + age + ' years old')
}
```

**Comment by mixmix** [comment]
I think my vim setup picks up some eslint things from Prettier and then starts highlighting everything it wants to change. I can probably look into it, as the interaction you describe is much better (though I still want some things highlighted when the code is broken and not just ugly, so you have that?)

**Comment by staltz** [comment]
> I think my vim setup picks up some eslint things from Prettier and then starts highlighting everything it wants to change.

Is it ESLint disagreeing with Prettier or something else? I think Prettier doesn't depend on ESLint when running.

> I can probably look into it, as the interaction you describe is much better (though I still want some things highlighted when the code is broken and not just ugly, so you have that?)

Try these different vim solutions:

- https://github.com/prettier/vim-prettier
- https://github.com/sbdchd/neoformat
- https://github.com/w0rp/ale
- https://github.com/neoclide/coc-prettier

**Comment by davegomez** [comment]
Prettier and ESLint are not compatible by default:

> Linters usually contain not only code quality rules, but also stylistic rules. Most stylistic rules are unnecessary when using Prettier, but worse – they might conflict with Prettier! Use Prettier for code formatting concerns, and linters for code-quality concerns, as outlined in [Prettier vs. Linters](https://prettier.io/docs/en/comparison.html).

If we want to use Prettier + ESLint we will need to define our own set of rules for ESLint or follow some of the Prettier recommendations.

https://prettier.io/docs/en/integrating-with-linters.html#docsNav

I still think creating an independent library to handle this is the best option. I'll work on a library proposal and let you know once I have ready.

**Comment by staltz** [comment]
@davegomez Good point! Wouldn't it be enough to use https://github.com/prettier/eslint-config-prettier#eslint-config-prettier ?

> Turns off all rules that are unnecessary or might conflict with Prettier.

**Comment by christianbundy** [comment]
> Linters usually contain not only code quality rules, but also stylistic rules.

Is this true with ESLint:Recommended? One of the reasons I proposed this pair (rather than an all-in-one solution like Standard) is the separation of concerns:

- ESLint and Prettier rules should never conflict because one checks code quality rules (semantics) and the other checks formatting (syntax).
- Your editor should never warn you about formatting, the format should just be normalized on save / commit.

If ESLint:Recommended conflicts with Prettier I'd be very curious to hear where. I've been using both together for a while and never experienced any incompatibilities.

**Comment by staltz** [comment]
> If ESLint:Recommended conflicts with Prettier I'd be very curious to hear where. I've been using both together for a while and never experienced any incompatibilities.

Sounds like a moment to merge this PR, then? We could discuss the technicalities separately. Now we have everyone onboard, we can help out Mix to setup something that doesn't irritate him.

**Comment by davegomez** [comment]
As @staltz pointed out, Prettier provides an ESLint configuration that doesn't clash with Prettier rules (is the one I use) and it just disables some stylistic rules that Prettier handles differently from ESLint.

For the automatic formatting, I recommend using extensions for your editor. In particular, for VSCode I can recommend:

- [Prettier Formatter for Visual Studio Code](https://github.com/prettier/prettier-vscode)
- [Formatting Toggle](https://github.com/Tom-Bonnike/vscode-formatting-toggle)

**Comment by christianbundy** [comment]
> Sounds like a moment to merge this PR, then?

:+1:, I was waiting for someone else to merge!

> Prettier provides an ESLint configuration that doesn't clash with Prettier rules 

Right, but ESLint:Recommended doesn't turn those rules on, so I don't think we need a plugin to disable them. Please let me know if there's a specific rule that we need to disable!

**Comment by christianbundy** [comment]
Shameless plug for tooling to automate ESlint + Prettier with no config or boilerplate: https://github.com/christianbundy/common-good

**Comment by mixmix** [comment]
Love the distinction between pointing and style formatting.
I have been using ale, and when I tried Prettier it was with a default setup for vue - _think_ I remember eslint recommended in that setup. Really excited to see Prettier working well.
Also interested in trying common-good (though wonder how that's gong to get maintained - we might end up moving it to ssb-js?!)

Thanks all for listening and exploring my no, this felt good

**Pull request merged**
