### PR TITLE
Remove draft status, add maintainers and projects

### PR DESCRIPTION
**Pull request by christianbundy**
Problem: The scope of this document includes nothing and no one.

Solution: Remove the draft status from the agreement and add maintainers
and projects to its scope. This commit should only be merged with
unanimous consent from the proposed maintainers.

Approvals:

- [x] @arj03
- [x] @christianbundy
- [x] @mixmix
- [x] @soapdog
- [x] @staltz

### CODE REVIEW

**Comment by christianbundy** [comment]
Backlink: `%Dek7wa3HhvzX+dW8RX7qixqLMwB/T7xTEuDZzysVB00=.sha256`

**Comment by staltz** [comment]
👍 from me

**Comment by mixmix** [comment]
:+1: from me.

I've got two things I'd like to add to this PR (or the next one)

**1. I would like to see at least 2 names next to each of these projects.**
This will force us to try out what that feels like, and also prevent us from accidentally slipping into the state we are in with SSBC where there are m owners, n modules, and heaps of PRs sitting around and falling through cracks.

**2. I would like to put a time limit on this**
> We MUST remove and manually add back ALL maintainers and ALL projects at Jan 31st 2021. All commitments after that point will be contained in pull-requests which follow.

(see `%BhaX8GGC+jOYIXDx6WC18+UTAkjmC4qAeNuWrdGQUQ8=.sha256` where I expand on why I'm keen on this)

**Comment by arj03** [comment]
👍 

I like that this is well structured. I was a bit wary of the changes on PRs, but then I re-read again and I'm 100% behind that. This is great!

**Comment by soapdog** [comment]
👍 this looks very good to me. I think we're ready.

**Comment by staltz** [comment]
@christianbundy Can you make all maintainers "owners" of the ssb-js GH org? It's not something written down in the org constitution, but maybe it should be.

Motivation: I was going to edit the ssb-js avatar :stuck_out_tongue:

**Comment by christianbundy** [comment]
Thanks all! I've just taken some actions:

- Invited you all to the SSB-JS organization.
  - I've changed the roles of current members (soapdog & staltz) to owners, I'll change arj and mix when they join. 
  - @staltz Would you mind making a PR for this?
    - Bonus points for specifying both GitHub and NPM.
    - Bonus bonus points (IMO) for mandatory 2FA for owners.
- Transferred the modules from SSBC to SSB-JS on GitHub and NPM.
- Revoked write access to GitHub and NPM modules from non-maintainers.
  - Can't remove dominictarr from Chloride: https://www.npmjs.com/package/chloride/access
  - Can't remove mmckegg, dominictarr, marak, pfraze, cel, substack, ahdinosaur, or cryp7ix from SSB-Ref: https://www.npmjs.com/package/ssb-ref/access
  - I've reached out to NPM support to resolve this.
- Opened issues for suggestions from @mixmix to discuss those suggestions outside of this PR: https://github.com/ssb-js/ssb-js/issues/2

**Comment by mixmix** [comment]
<3

**Comment by staltz** [comment]
>   - @staltz Would you mind making a PR for this?
>    - Bonus points for specifying both GitHub and NPM.
>    - Bonus bonus points (IMO) for mandatory 2FA for owners.

@christianbundy I'm sorry, make a PR for what? And what are these bonus points?

**Comment by christianbundy** [comment]
@staltz 

> I'm sorry, make a PR for what? And what are these bonus points?

Oops, I was referring to when you said this:

> Can you make all maintainers "owners" of the ssb-js GH org? It's not something written down in the org constitution, but maybe it should be.

It would be great to have language like:

- All maintainers MUST have the 'owner' role in the SSB-JS organizations on GitHub and NPM.
- All maintainers MUST have 2FA enabled on GitHub and NPM.

**Pull request merged**
